name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  release:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Install rollup
        run: npm i -g rollup
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          versioning-strategy: always-bump-patch
      - name: bundle
        run: npm run rollup
      - name: configure npm
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - name: Publish package on npmjs 📦
        run: npm publish
    env: 
      NPM_TOKEN: ${{ secrets.NPMJS_SECRET }}
      
